# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b37b5ae11eea271184c9f9101e007c71d8bb7fb87404dde8c396ccbfacf0b81a6ed5ffda29a6e4b4e899f9b1228f265cb0f8cb095b4f2576c4332e92daee0a8d

test:
  secret_key_base: fdbee7cc6799ca6d54ae82f62e82c7ad274b65ded5044072dde14bb8e95834adcb56a2b7e35874b1936738273400f56afa95e42f359e4cbf0b5ee49166be767e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
